"""create_all_tables

Revision ID: 2eb0c3e09fb3
Revises: 
Create Date: 2026-06-17 00:57:54.029517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2eb0c3e09fb3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consent',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('perimeter', sa.Enum('ALL', 'PRESCRIPTIONS', name='perimeter'), nullable=False),
    sa.Column('granted_at', sa.Date(), nullable=False),
    sa.Column('expire_at', sa.Date(), nullable=False),
    sa.Column('duration', sa.Enum('MIN_30', 'H_1', name='duration'), nullable=False),
    sa.Column('is_actif', sa.Boolean(), nullable=False),
    sa.Column('is_urgence', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('diagnosisreference',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code_cid11', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('libelle', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diagnosisreference_code_cid11'), 'diagnosisreference', ['code_cid11'], unique=True)
    op.create_table('healthcaresystem',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nom', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('alias', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_actif', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medicationreference',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code_medicament', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nom_commercial', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('dc_nom', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('forme_galenique', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medicationreference_code_medicament'), 'medicationreference', ['code_medicament'], unique=True)
    op.create_table('patient',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_user_id'), 'patient', ['user_id'], unique=True)
    op.create_table('practitioner',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('speciality', sa.Enum('MEDECIN', 'INFIRMIER', 'CHIRURGIEN', 'PEDIATRE', 'GYNECOLOGUE', 'RADIOLOGUE', 'BIOLOGISTE', 'PHARMACIEN', 'DENTISTE', 'AUTRE', name='speciality'), nullable=False),
    sa.Column('order_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('organization_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_practitioner_user_id'), 'practitioner', ['user_id'], unique=True)
    op.create_table('vitalconstantreference',
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nom', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('unite_mesure', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('dmn',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('date_creation', sa.DateTime(), nullable=False),
    sa.Column('blood_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('rhesus_factor', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('patient_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id')
    )
    op.create_table('practitionerrole',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('practitioner_id', sa.Uuid(), nullable=True),
    sa.Column('health_care_system_id', sa.Uuid(), nullable=True),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['health_care_system_id'], ['healthcaresystem.id'], ),
    sa.ForeignKeyConstraint(['practitioner_id'], ['practitioner.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('authorization',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('perimeter', sa.Enum('ALL', 'PRESCRIPTIONS', name='perimeter'), nullable=False),
    sa.Column('granted_at', sa.Date(), nullable=False),
    sa.Column('expire_at', sa.Date(), nullable=False),
    sa.Column('duration', sa.Enum('MIN_30', 'H_1', name='duration'), nullable=False),
    sa.Column('is_actif', sa.Boolean(), nullable=False),
    sa.Column('is_urgence', sa.Boolean(), nullable=False),
    sa.Column('authorization_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('granted_by', sa.Uuid(), nullable=True),
    sa.Column('dmn_id', sa.Uuid(), nullable=True),
    sa.Column('practitioner_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['dmn_id'], ['dmn.id'], ),
    sa.ForeignKeyConstraint(['practitioner_id'], ['practitioner.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medicalact',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('raisons', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('rapport_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('observations_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('dmn_id', sa.Uuid(), nullable=True),
    sa.Column('practitioner_role_id', sa.Uuid(), nullable=True),
    sa.Column('type', sa.Enum('CONSULTATION', 'CHIRURGIE', 'EXAMEN', 'VACCINATION', 'AUTRE', name='typeacte'), nullable=False),
    sa.ForeignKeyConstraint(['dmn_id'], ['dmn.id'], ),
    sa.ForeignKeyConstraint(['practitioner_role_id'], ['practitionerrole.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('consultation',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('duree_minutes', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['medicalact.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('diagnosis',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('statut_verification', sa.Enum('CONFIRMED', 'SUSPECTED', 'REJECTED', name='diagnosisverification'), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('note_clinique', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('medical_act_id', sa.Uuid(), nullable=True),
    sa.Column('diagnosis_ref_id', sa.Uuid(), nullable=True),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['diagnosis_ref_id'], ['diagnosisreference.id'], ),
    sa.ForeignKeyConstraint(['medical_act_id'], ['medicalact.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('emergencycontact',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('authorization_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['authorization_id'], ['authorization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('examinationact',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code_loinc', sa.String(), nullable=False),
    sa.Column('libelle_examen', sa.String(), nullable=False),
    sa.Column('type_examen', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('interpretation', sa.String(), nullable=False),
    sa.Column('image_path', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['medicalact.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prescriptionorder',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('date_emission', sa.DateTime(), nullable=False),
    sa.Column('statut', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('medical_act_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['medical_act_id'], ['medicalact.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('medical_act_id')
    )
    op.create_table('vaccination',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('injection_site', sa.String(), nullable=True),
    sa.Column('sequence_dose', sa.Integer(), nullable=True),
    sa.Column('batch_number', sa.String(), nullable=True),
    sa.Column('next_reminder', sa.Date(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['medicalact.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vitalconstant',
    sa.Column('medical_act_id', sa.Uuid(), nullable=False),
    sa.Column('vital_constant_reference_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date_mesure', sa.DateTime(), nullable=False),
    sa.Column('valeur', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['medical_act_id'], ['medicalact.id'], ),
    sa.ForeignKeyConstraint(['vital_constant_reference_code'], ['vitalconstantreference.code'], ),
    sa.PrimaryKeyConstraint('medical_act_id', 'vital_constant_reference_code')
    )
    op.create_table('allergy',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nature_allergie', sa.String(), nullable=False),
    sa.Column('categorie', sa.String(), nullable=False),
    sa.Column('libelle', sa.String(), nullable=False),
    sa.Column('criticite', sa.String(), nullable=False),
    sa.Column('statut_clinique', sa.String(), nullable=False),
    sa.Column('discover_at', sa.Date(), nullable=False),
    sa.Column('reactions_text', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['diagnosis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('careepisode',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('clinical_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('severity', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('diagnosis_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['diagnosis_id'], ['diagnosis.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('diagnosis_id')
    )
    op.create_table('disease',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['diagnosis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prescription',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('date_prescription', sa.DateTime(), nullable=False),
    sa.Column('statut', sa.Enum('EN_COURS', 'DISPENSE', 'ANNULE', 'TERMINE', name='statutprescription'), nullable=False),
    sa.Column('special_instructions', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('diagnosis_id', sa.Uuid(), nullable=True),
    sa.Column('type_prescription', sa.Enum('VACCIN', 'EXAMINATION', name='typeprescription'), nullable=False),
    sa.ForeignKeyConstraint(['diagnosis_id'], ['diagnosis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prescriptiondirective',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('description_generale', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prescription_order_id', sa.Uuid(), nullable=False),
    sa.Column('type_directive', sa.Enum('MEDICAMENT', 'SOINS_REED_KINE', 'MODE_DE_VIE', name='typedirective'), nullable=False),
    sa.ForeignKeyConstraint(['prescription_order_id'], ['prescriptionorder.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('relatedperson',
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('emergency_contact_id', sa.Uuid(), nullable=False),
    sa.Column('code_relation', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['emergency_contact_id'], ['emergencycontact.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('patient_id', 'emergency_contact_id')
    )
    op.create_table('examination',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code_loinc', sa.String(), nullable=False),
    sa.Column('libelle', sa.String(), nullable=False),
    sa.Column('nature_examination', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['prescription.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lifestyledirective',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('titre_consigne', sa.String(), nullable=False),
    sa.Column('recommandations', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['prescriptiondirective.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medicationdirective',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('medication_ref_id', sa.UUID(), nullable=False),
    sa.Column('posologie', sa.String(), nullable=False),
    sa.Column('duree_jours', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['prescriptiondirective.id'], ),
    sa.ForeignKeyConstraint(['medication_ref_id'], ['medicationreference.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessiondirective',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre_seances', sa.Integer(), nullable=False),
    sa.Column('frequence_hebdo', sa.String(), nullable=False),
    sa.Column('objectifs_specifiques', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['prescriptiondirective.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vaccine',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code_cvx', sa.String(), nullable=False),
    sa.Column('libelle', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['prescription.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vaccine')
    op.drop_table('sessiondirective')
    op.drop_table('medicationdirective')
    op.drop_table('lifestyledirective')
    op.drop_table('examination')
    op.drop_table('relatedperson')
    op.drop_table('prescriptiondirective')
    op.drop_table('prescription')
    op.drop_table('disease')
    op.drop_table('careepisode')
    op.drop_table('allergy')
    op.drop_table('vitalconstant')
    op.drop_table('vaccination')
    op.drop_table('prescriptionorder')
    op.drop_table('examinationact')
    op.drop_table('emergencycontact')
    op.drop_table('diagnosis')
    op.drop_table('consultation')
    op.drop_table('medicalact')
    op.drop_table('authorization')
    op.drop_table('practitionerrole')
    op.drop_table('dmn')
    op.drop_table('vitalconstantreference')
    op.drop_index(op.f('ix_practitioner_user_id'), table_name='practitioner')
    op.drop_table('practitioner')
    op.drop_index(op.f('ix_patient_user_id'), table_name='patient')
    op.drop_table('patient')
    op.drop_index(op.f('ix_medicationreference_code_medicament'), table_name='medicationreference')
    op.drop_table('medicationreference')
    op.drop_table('healthcaresystem')
    op.drop_index(op.f('ix_diagnosisreference_code_cid11'), table_name='diagnosisreference')
    op.drop_table('diagnosisreference')
    op.drop_table('consent')
    # ### end Alembic commands ###
